
raw_sim_folder: "raw-simulations/20220203_simulations"
epochs_for_model_training: 25
validation_percentage: 0.2
sims_per_regime: 5000

training_ids:
  - simple

inference_targets:
  - log-sel-strength
