
raw_sweep_region_vcf: "raw-data/20211130_sweep-region/high_cov.SNP1.hg19_chr8.phased_STC1.vcf.recode.vcf"

sweep_chromosome: 8
sweep_region_start: 23350029 
sweep_region_end: 24424864

stats_file_location: "resources/normalization-stats.tsv"

raw_sim_folder: "raw-simulations/20220421_simulations"
epochs_for_model_training: 50
validation_percentage: 0.2
sims_per_regime: 5000

num_model_replicates: 10

training_ids:
  - codominant
  - dominant

inference_targets:
  - log-sel-strength
  - sweep-mode
  # - hard-vs-soft
  # - rnm-vs-sgv
  # - sweep-age
  # - sgv-f0
  # - rnm-num-mutations
  - sgv-drift-time
  - sgv-total-time
  - num-adaptive-alleles
